@startuml クラス図
left to right direction

package 座席監視アプリ {
    class "SeatMonitoringApplication" as SeatMonitoringApplication {
        + main():void
    }

    class "Configration" as ClientConfigration {
		- ipAddress
        + set():void
    }

	class "Screen" as Screen {
        + show(Configration):void
        + update(List<SeatStatus>):void
		+ close():void
    }

    class "SeatMonitoringApiClient" as SeatMonitoringApiClient {
        + get(Configration):List<SeatStatus>
    }

    class "RegularNortifier" as RegularNortifier {
        - destination
        - stopFlag
        + RegularNortifier(update())
        + start(Configration):void
        + execute(Configration):void
        + stop():void
    }
        note top of RegularNortifier
            ・定期的に座席状態の更新を通知するクラス
            ・コンストラクタで通知先を登録する
            ・executeメソッドから1分毎に座席の状態をdestinationに通知する
        end note

    class "SeatStatus" as SeatStatus {
        - seatName
        - humanExist
    }
}

package SeatMonitoringApi {
    class "SeatsController" as SeatsController {
        + initialize():void
        + seats():座席情報のオブジェクト
    }
    
    class "Configration" as ServerConfigration {
        - seatsInformation
        + set():void
    }

    class "Photographer" as Photographer {
        + get(Configration):Configration
    }
    
    class "SeatInformation" as SeatInformation {
        - seatName
        - humanExist
        - moniker
        - picture
    }
    
    class "HumanDetector" as CsHumanDetector {
        + execute(Configration):Configration
    }
}

package CppDll {
    class "HumanDetector" as CppHumanDetector {
        + execute(picture):boolean
    }
}

SeatMonitoringApplication -- ClientConfigration
SeatMonitoringApplication -left- Screen
Screen -down- RegularNortifier
RegularNortifier -down- SeatMonitoringApiClient
RegularNortifier .> ClientConfigration
RegularNortifier .left.> SeatStatus
Screen .> SeatStatus
Screen .> ClientConfigration
SeatMonitoringApiClient .left.> ClientConfigration
SeatMonitoringApiClient "1"-left-"0..10" SeatStatus
SeatMonitoringApiClient -- SeatsController
ServerConfigration "1"*-down-"0..10" SeatInformation
SeatsController -- ServerConfigration
SeatsController -- Photographer
SeatsController -- CsHumanDetector
CppHumanDetector -- CsHumanDetector
Photographer .> ServerConfigration
CsHumanDetector .> ServerConfigration

@enduml