@startuml SeatMonitoringAPI起動シーケンス図
hide footbox

participant "WebApiApplication" as WebApiApplication
participant "Configuration" as Configuration
participant "SeatDefinition" as SeatDefinition

note over WebApiApplication
	ASP.NETで提供されているクラス
	Webサーバに読み込まれるときにApplication_Start()
	メソッドで起動のための初期処理を行う
end note
-> WebApiApplication :Webサーバからの読み込み\nApplication_Start()
activate WebApiApplication

create Configuration
WebApiApplication -> Configuration : new Configuration()
activate Configuration

alt ファイル読み込みに成功
	loop
		create SeatDefinition
		Configuration -> SeatDefinition :new SeatDefinition(name:string, moniker:string)
	end
	note right
		Configurationのコンストラクタでファイルを読み、
		読み込んだ監視座席数分のインスタンスのリストを作成する
		Seatのコンストラクタはnameとmonikerを
		引数に受け取って初期化を行う
	end note
|||
else ファイル読み込みに失敗
	deactivate Configuration
	deactivate WebApiApplication
	note over WebApiApplication
		アプリケーションの起動が中止される
	end note
end

@enduml