@startuml 座席監視アプリ起動シーケンス図
hide footbox

participant "SeatMonitoringApplication" as SeatMonitoringApplication
participant "Screen" as Screen

-> SeatMonitoringApplication :Main()
activate SeatMonitoringApplication

create SeatMonitoringApiClient
SeatMonitoringApplication -> SeatMonitoringApiClient : new ToastNotifier(host:string)
note right
	app.configファイルからホストを読み込み、
	コンストラクタに引数として渡す
end note

create PeriodicNotifier
SeatMonitoringApplication -> PeriodicNotifier : new PeriodicNotifier(SeatMonitoringApiClient)

note over SeatMonitoringApiClient
	app.configファイルから通知設定を読み込み、
	通知先の登録を行う
end note

alt 通知設定がON
	create MyToastNotificationManager
	SeatMonitoringApplication -> MyToastNotificationManager : new

	create ToastNotifier
	SeatMonitoringApplication -> ToastNotifier : new ToastNotifier(MyToastNotificationManager)
	note over SeatMonitoringApiClient
		ToastNotifierクラスのNotifyメソッドをPeriodicNotifierクラスのdestinationに追加する
	end note
else 通知設定がOFF

end


alt ファイル読み込みに成功
	create Screen
	SeatMonitoringApplication -> Screen : new Screen(periodicNotifier:PeriodicNotifier)
	note right
		コンストラクタでScreenクラスのUpdateメソッドをPeriodicNotifierクラスのdestinationに追加する
	end note
	SeatMonitoringApplication -> Screen : Show()
	activate Screen
	SeatMonitoringApplication <- Screen
	deactivate Screen
else ファイル読み込みに失敗
	note over SeatMonitoringApplication
		エラーダイアログを表示し、
		OKボタン押下でアプリケーションを終了する
	end note
	deactivate SeatMonitoringApplication
end

@enduml