@startuml 座席状態確認シーケンス図
hide footbox

participant "Screen" as Screen
participant "PeriodicNotifier" as PeriodicNotifier

-> Screen :Show()
Screen -> Screen :画面表示イベント
activate Screen

Screen -> PeriodicNotifier :Start()
activate PeriodicNotifier
Screen <- PeriodicNotifier
deactivate PeriodicNotifier
deactivate Screen
note right
	1分毎に以下の処理を非同期に行う
	・座席の写真を撮影
	・撮影した写真から座席状態を確認
	・確認結果で画面を更新、状態の変化を通知する
	詳細を別図(座席状態確認シーケンス図2)に示す
end note

@enduml