@startuml SeatMonitoringAPI起動シーケンス図
hide footbox

participant "SeatMonitoringApiController" as SeatMonitoringApiController
participant "Configration" as Configration
participant "SeatInformation" as SeatInformation

-> SeatMonitoringApiController :起動イベント initialize()
activate SeatMonitoringApiController

create Configration
SeatMonitoringApiController -> Configration : new Configration()
activate Configration

alt ファイル読み込みに成功
	loop
		create SeatInformation
		Configration -> SeatInformation :new SeatInformation(string, string)
	end
	note right
		Configrationのコンストラクタでファイルを読み、
		読み込んだ監視座席数分のインスタンスのリストを作成する
		SeatInformationのコンストラクタはseatNameとmonikerを
		引数に受け取って初期化を行う
	end note
|||
else ファイル読み込みに失敗
	SeatMonitoringApiController -> SeatMonitoringApiController :end()
	deactivate Configration
	deactivate SeatMonitoringApiController
	note right
		アプリケーションを終了させる
	end note
end

@enduml