@startuml システム終了シーケンス図
hide footbox

participant "Screen" as Screen
participant "RegularNortifier" as RegularNortifier

-> Screen :closeイベント close()
activate Screen
Screen -> RegularNortifier :stop()
activate RegularNortifier
Screen <- RegularNortifier
deactivate RegularNortifier
note right
	stopFlagを立てて
	executeメソッドを終了させる
end note
note left
	Screenのcloseメソッド終了後、
	Screen:showメソッドが終了して画面が閉じ、
	SeatMonitoringApplication:mainメソッドが終了する
end note

@enduml