@startuml 座席監視アプリ起動シーケンス図
hide footbox

participant "SeatMonitoringApplication" as SeatMonitoringApplication
participant "Configration" as Configration
participant "Screen" as Screen

-> SeatMonitoringApplication :main()
activate SeatMonitoringApplication
create Configration
SeatMonitoringApplication -> Configration : new
note right
	コンストラクタでinitializeメソッドを呼び出し、
	ファイルからアクセスするサーバのIPアドレスを取得して
	フィールドにセットする
end note

create Screen
	SeatMonitoringApplication -> Screen : new

alt ファイル読み込みに成功
	SeatMonitoringApplication -> Screen : show(Configration)
	activate Screen
	SeatMonitoringApplication <- Screen
	deactivate Screen
else ファイル読み込みに失敗
	SeatMonitoringApplication -> Screen :initializeError()
	activate Screen
	SeatMonitoringApplication <- Screen
	deactivate Screen
	deactivate SeatMonitoringApplication
	note right
		エラーメッセージを表示し、
		OKボタン押下でアプリケーションを終了する
	end note
end

@enduml