@startuml 座席監視アプリ起動シーケンス図
hide footbox

participant "SeatMonitoringApplication" as SeatMonitoringApplication
participant "Configration" as Configration
participant "Screen" as Screen

-> SeatMonitoringApplication :Main()
activate SeatMonitoringApplication
create Configration
SeatMonitoringApplication -> Configration : new
note right
	コンストラクタでファイルからアクセスする
	サーバのIPアドレスを取得してフィールドにセットする
end note

alt ファイル読み込みに成功
	create Screen
	SeatMonitoringApplication -> Screen : new
	SeatMonitoringApplication -> Screen : Show(Configration)
	activate Screen
	SeatMonitoringApplication <- Screen
	deactivate Screen
else ファイル読み込みに失敗
	note over SeatMonitoringApplication
		エラーメッセージを表示し、
		OKボタン押下でアプリケーションを終了する
	end note
	deactivate SeatMonitoringApplication
end

@enduml