@startuml 座席監視アプリ起動シーケンス図
hide footbox

participant "SeatMonitoringApplication" as SeatMonitoringApplication
participant "Configration" as Configration
participant "Screen" as Screen

-> SeatMonitoringApplication :main()
activate SeatMonitoringApplication
SeatMonitoringApplication -> Configration : set()
activate Configration
SeatMonitoringApplication <- Configration
deactivate Configration
note right
	ファイルからアクセスするサーバの
	IPアドレスを取得し、フィールドにセットする
end note

SeatMonitoringApplication -> Screen : show(Configration)
activate Screen
SeatMonitoringApplication <- Screen
deactivate Screen
deactivate SeatMonitoringApplication

@enduml