@startuml 座席状態確認シーケンス図2
hide footbox
skinparam BoxPadding 20

box "座席監視アプリ"
	participant "RegularNortify" as RegularNortify
	participant "SeatMonitoringApiClient" as SeatMonitoringApiClient
	participant "SeatStatus" as SeatStatus
	participant "Screen" as Screen
end box

box "SeatMonitoringAPI"
	participant "SeatsController" as SeatsController
	participant "Photographer" as Photographer
	participant "HumanDetector" as CsHumanDetector
	participant "HumanDetector" as CppHumanDetector
end box

-> RegularNortify :start(Configratinon)
note right
	座席監視アプリのConfigrationクラスは
	接続するサーバのIPアドレスをメンバに持つ
end note

RegularNortify -> RegularNortify : execute(Configration)
activate RegularNortify

loop stopFlagがfalseの間
	RegularNortify -> SeatMonitoringApiClient : get()
	activate SeatMonitoringApiClient

	SeatMonitoringApiClient -> SeatsController : seats()
	activate SeatsController

	note right
		SeatMonitoringAPIのConfigrationクラスは
		SeatInformationクラスのリストをメンバに持つ

		SeatInformationクラスは以下のメンバを持つ
		・seatName(監視座席名)
		・humanExist(座席状態)
		・moniker(モニカ(デバイスインスタンスパス))
		・picture(画像)
	end note

	SeatsController -> Photographer : get(Configration)
	activate Photographer
	SeatsController <- Photographer : "Configration"
	deactivate Photographer
	note right
		monikerでカメラを指定して画像を取得し、
		pictureに格納する
	end note

	SeatsController -> CsHumanDetector : execute(Configration)
	activate CsHumanDetector

	loop 監視座席数
		CsHumanDetector -> CppHumanDetector : execute(picture)
		activate CppHumanDetector
		CsHumanDetector <- CppHumanDetector : "result"
		deactivate CppHumanDetector
	end
	note right
		監視座席数分の画像を1枚ずつ判定し、
		結果をhumanExistに反映する
	end note
	
	SeatsController <- CsHumanDetector : "Configration"
	deactivate CsHumanDetector

	SeatMonitoringApiClient <- SeatsController : "座席情報のオブジェクト"
	deactivate SeatsController

	loop 監視座席数
		SeatMonitoringApiClient -> SeatStatus :new
	end
	note right
		監視座席数分のインスタンスを作成し、
		リストを作成する

		SeatStatusクラスは以下のメンバを持つ
		・seatName(監視座席名)
		・humanExist(座席状態)
	end note

	RegularNortify <- SeatMonitoringApiClient : "List<SeatStatus>"
	deactivate SeatMonitoringApiClient
	|||
	RegularNortify -> Screen : update(List<SeatStatus>)
	activate Screen
	RegularNortify <- Screen
	deactivate Screen
	deactivate RegularNortify
end

@enduml