@startuml ユースケース図
left to right direction
actor ユーザ
actor システム管理者

rectangle システム {
	rectangle クライアント {
		ユーザ -- (<<UC01>> \n クライアントアプリ起動)
		ユーザ -- (<<UC02>> \n 監視座席に人がいるか確認)
		ユーザ -- (<<UC03>> \n クライアントアプリ終了)
	}

	rectangle サーバ {
		(<<UC04>> \n サーバアプリ起動) -- システム管理者
		(<<UC02>> \n 監視座席に人がいるか確認) ..> (<<UC05>> \n 監視座席に人がいるか確認) : <<invokes>>
		(<<UC06>> \n 監視座席の追加) -- システム管理者
		(<<UC07>> \n 監視座席の削除) -- システム管理者
		(<<UC08>> \n サーバアプリ終了) -- システム管理者
	}
}
@enduml