@startuml ユースケース図
left to right direction
actor ユーザ
actor システム管理者

rectangle システム {
	rectangle クライアント {
		ユーザ -- (<<UC-C01>> \n 座席監視システム起動)
		ユーザ -- (<<UC-C02>> \n 監視座席に人がいるか確認)
		ユーザ -- (<<UC-C03>> \n 座席監視システム終了)
	}

	rectangle サーバ {
		(<<UC-S01>> \n Seat Monitoring API起動) -- システム管理者
		(<<UC-C02>> \n 監視座席に人がいるか確認) ..> (<<UC-S02>> \n 監視座席に人がいるか確認) : <<invokes>>
		(<<UC-S03>> \n 監視座席の追加) -- システム管理者
		(<<UC-S04>> \n 監視座席の削除) -- システム管理者
		(<<UC-S05>> \n Seat Monitoring API終了) -- システム管理者
	}
}
@enduml