@startuml 画面遷移図

state 画面遷移図 {
	[*] --> アプリ画面 :座席監視アプリ起動
	アプリ画面 --> 監視画面 :監視開始ボタン押下
	アプリ画面 --> サーバエラー画面 :サーバに接続できない場合
	アプリ画面 --> [*] :「アプリ終了」ボタン押下
	アプリ画面 : 「監視開始」ボタン
	アプリ画面 : 「監視終了」ボタン
	アプリ画面 : 「アプリ終了」ボタン

	監視画面 --> アプリ画面 :監視終了ボタン押下
	監視画面 : 監視座席の状態表示

	サーバエラー画面 --> [*] :OKボタン押下
	サーバエラー画面 : 「OK」ボタン
}

@enduml